name: Build

on:
  pull_request:
  push:
    branches: ["main", "dev"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v5
        with:
          go-version: 1.20 # The Go version to download (if necessary) and use.
      - name: Build CLI
        run: go install ./...
