name: Test

on:
  pull_request:
  push:
    branches: ["main", "dev"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22 # The Go version to download (if necessary) and use.
      - name: Test
        shell: bash
        run: go test ./...
